### ISSUE TITLE
Conflict with Navigraph data

### ISSUE THREAD

**Issue by frankkopp** [gravity-EDDS/EDDS-freeware-releases#7] opened 2020-12-08 11:34 UTC
**Describe the bug**
Great work!
Unfortunately conflicts with Navigraph data.
See screenshots

**To Reproduce**
1: Install Navigraph AIRAC 2013 for MSFS
2. Goto EDDS look from Rwy25 where you can see the issues best

**Screenshots**
![image](https://user-images.githubusercontent.com/16833201/101478632-43f20200-3951-11eb-869b-be7c057a7860.png)
![image](https://user-images.githubusercontent.com/16833201/101478698-5d934980-3951-11eb-9329-231e216a7c87.png)
4a
![image](https://user-images.githubusercontent.com/16833201/101478778-7e5b9f00-3951-11eb-9472-44d3ee6a3993.png)
![image](https://user-images.githubusercontent.com/16833201/101478842-97645000-3951-11eb-9388-9bf9f53bd75a.png)

**Additional context**
It seems that MSFS creates a default runway without buildings for EDDS based on Navigraph data. 
This results in different elevations and graphic renderings are partly doubled. 
Maybe separating airport (buildings, etc.) from the nav data so they can be installed separately?

**Comment by foxmike80** [comment] 2020-12-21 11:14
I was in touch with the guys from navigraph and they are about to release a new version of the installer which will fix the issue.
However, he mentioned in the thread that nav data should be separate from scenery and was wondering why gravity have inculded the navdata in their scenery. Here is the link:
https://forum.navigraph.com/t/multiple-addon-sceneries-priorities-and-the-double-runway-effect/2357/7

**Comment by nsteffens** [comment] 2020-12-22 16:14
Hey there!

As discussed on our discord, we can check if we split it up into a nav-data project and a scenery-only. Through this, navigraph and non-navigraph users would be enabled to use this.

However, we have reports of users that have the navigraph data and our airport without any issues.

Furthermore, I can confirm, that indeed in the current version this line is included:
```
<DeleteAirport deleteAllApproaches="TRUE" deleteAllApronLights="TRUE" deleteAllAprons="TRUE" deleteAllFrequencies="TRUE" deleteAllHelipads="TRUE" deleteAllRunways="TRUE" deleteAllStarts="TRUE" deleteAllTaxiways="TRUE" deleteAllBlastFences="TRUE" deleteAllBoundaryFences="TRUE" deleteAllJetways="TRUE" deleteAllControlTowers="TRUE" deleteAllDepartures="FALSE" deleteAllArrivals="FALSE" deleteAllPaintedElements="FALSE" deleteAllLightSupports="TRUE" deleteAllTaxiwaySigns="FALSE" deleteAllILSs="FALSE" deleteAllTerminalWaypoints="FALSE" deleteAllTerminalNDBs="FALSE"/>
```

I'll check what we can do about this :-).

**Comment by frankkopp** [comment] 2020-12-23 11:13
I could fix it with the new Navigraph revision by uninstalling Navigraph data and the EDDS mod. Then deleting content.xml, starting the sim. Shutting sim down and re-install nav data and EDDS. Now it looks ok.

**Comment by lakemike** [comment] 2020-12-27 12:31
I can confirm the problem is real. On my end, it occurred after installing latest Navigraph (beta) for MSFS, then adding gravity's EDDS. You can notice it already in the flight plan menu, because there will be only runways but no gates or parking positions visible.

![edds-broken](https://user-images.githubusercontent.com/62221234/103170818-93886700-4847-11eb-87d8-ac4ba880b19e.png)

I could somewhat fix it by renaming the addon folder to "zzz-gravity-airport-edds-stuttgart". MSFS is loading addon folders in alphabetical order and this prefix will ensure it gets read after the navigraph files.

![edds-fixed](https://user-images.githubusercontent.com/62221234/103170821-9a16de80-4847-11eb-92cd-b4fa9067d91d.png)

But unfortunately, there are still issues. 1) when I select EDDS in the flight plan tool, I get an error message that I am no longer connected to internet (no screenshot, sorry) and 2) once loaded and on the airport, I get an error message that "packages are out of date" and I shall go back to "sign-in screen". This stops again when I remove the gravity addon.

![edds-still-broken](https://user-images.githubusercontent.com/62221234/103170824-9e42fc00-4847-11eb-82ad-951190bc229d.png)

**Comment by nsteffens** [comment] 2021-01-10 21:25
We've finally found the issue that is causing this. To fix this, follow these instructions that I also recently posted on our Discord server:

The "default" MSFS without Stuttgart and/or Navigraph includes no Waypoints for and around Stuttgart. These are added redundant by us and Navigraph. This can result in issues, since Navigraph also adds a runway for Stuttgart (incl. the procedures). This conflicts with our airport that includes accurate slope and so causes these elevation glitches.

To prevent this from happening the following needs to be done:
- Two levels above your community folder, a file named `Content.xml` exists.
  - For me, this file is in `C:\Users\USERNAME\AppData\Roaming\Microsoft Flight Simulator`, my community folder is in `C:\Users\USER\AppData\Roaming\Microsoft Flight Simulator\Packages\Community`
- Open this file in an editor, preferably Notepad, VS Code, Notepad++ but not WordPad or Word!)
- Within this file you can find a list of all detected and loaded packages of the simulator. You'll also see the base-packages of Asobo there and the priority in which these are loaded. The top-most package is loaded first while the package at the bottom is loaded last.
- Since you, as a navigraph user, want to have the most recent AIRAC cycles and our airport, you need to load the navigraph data first and enable us to override the default runway of navigraph. You do this as follows:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
  ...
  <Package name="fs-base-nav" active="true"/>
  <Package name="navigraph-navdata" active="true"/>
  <Package name="gravity-airport-edds-stuttgart" active="true"/>
  ...
</Content>
```

- Now restart the simulator. This should solve the problem.

In the future, we can even improve this by moving the navigation data to an own .bgl that then can be removed by navigraph users. It's still quite annoying, but this seems to be the way to go right now. Asobo doesn't offer to force being loaded after a package (if it exists). Stuttgart is also a very special case since it's a larger airport that is completely missing (as described incl. all waypoints) from MSFS.

I hope this fixes the issue, will close this for now. If it's still present, feel free to comment.

**Closed as completed by nsteffens** 2021-01-10 21:25 UTC
